# Generated by Django 5.1.1 on 2026-01-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
